const data = {
    products:[
        {
            _id:'1',
            name:'Short Sleeve Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:60,
            countInStock: 10,
            brand:'Club Monaco', 
            rating: 4,
            numReviews:10,
            description:'100% Cotton',
        },
        {
            _id:'2',
            name:'Long Sleeve Shirt',
            category:'Shirts',
            image:'/images/p3.jpg',
            price:70,
            countInStock: 2,
            brand:'Fred Perry', 
            rating: 5,
            numReviews:15,
            description:'100% Cotton',
        },
        {
            _id:'3',
            name:'Sweater',
            category:'Sweater',
            image:'/images/p4.jpg',
            price:90,
            countInStock: 0,
            brand:'OVO', 
            rating: 5,
            numReviews:20,
            description:'100% Cotton',
        },
        {
            _id:'4',
            name:'Short Sleeve Shirt',
            category:'Shirts',
            image:'/images/p5.jpg',
            price:70,
            countInStock: 20,
            brand:'Fred Perry', 
            rating: 5,
            numReviews:12,
            description:'100% Cotton',
        },
        {
            _id:'5',
            name:'Slim Fit Jeans',
            category:'Bottoms',
            image:'/images/p2.jpg',
            price:70,
            countInStock: 20,
            brand:'Levi\'s', 
            rating: 4,
            numReviews:15,
            description:'100% Denim',
        },
        {
            _id:'6',
            name:'Men\'s Tank Top',
            category:'Shirts',
            image:'/images/p7.jpg',
            price:20,
            countInStock: 7,
            brand:'Calvin Klein', 
            rating: 4,
            numReviews:10,
            description:'100% Cotton',
        }
    ]
};
export default data;